name: well-binge

services:
  app:
    build: .
    image: ghcr.io/birabittoh/well-binge:main
    container_name: well-binge
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ./templates:/app/templates
#      - ./static:/app/static
#      - ./data:/app/data
